# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:db_civa_test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: 08af2447a30c9c090b3595e6b45cead32eb587dcb1892aae31f073dcb31bce95
    lifeTime: 631138000000
    user:
      generator: Civa

# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  level:
    root: INFO
    com.tu.paquete: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'