# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  jpa:
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_civa?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
flyway:
  enabled: true
  locations: classpath:/db/migration
  baseline-on-migrate: true
  baseline-version: 0

# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: 08af2447a30c9c090b3595e6b45cead32eb587dcb1892aae31f073dcb31bce95
    lifeTime: 631138000000
    user:
      generator: Civa

# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  level:
    root: INFO
    com.tu.paquete: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'